# The file is base class for US image classfication
# generated by wenzhilv
""" base class for US image process

"""

from uscnn import preprocess as uspreprocess
from uscnn import model as usmodel
from uscnn import train as ustrain
from uscnn import prediction as usprediction
from uscnn import evaluation as usevaluation

if __name__ == '__main__':
    print("run main for US image process")
else:
    print("uscnn package init")
